### ISSUE TITLE
Vocabulary set creation process

### ISSUE THREAD

**Issue by kanishkamisra** [alexwarstadt/data_generation#48]
Hi! Big fan of the NPI as well as BLiMP benchmark :D I was wondering how the vocabulary set was constructed.

I have been trying to find a citeable lexicon of verbs that also consists of information of the transitivity of the verb and the `vocabulary.csv` file might just solve a lot of my problems. If I end up using that file, what is a good citation to use? Just this repo or the NPI paper since technically it was first released for that work? 

Thanks!

**Comment by alexwarstadt** [comment]
Hi Kanishka! We recommend you cite the BLiMP paper, since most of the development on the repo occurred in connection with that project. I just added the citation info to the README. 

The vocabulary.csv file was constructed mostly manually. In fact, I think valex (https://ilexir.co.uk/valex/index.html) might potentially be a more useful resource than our vocabulary.

**Comment by kanishkamisra** [comment]
Thank you very much!
